apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "faucet.fullname" . }}
  labels:
    app: {{ template "faucet.name" . }}
    chart: {{ template "faucet.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "faucet.name" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      containers:
      - env:
        - name: FAUCET_CONFIG_STAT_RELOAD
        - name: FAUCET_EVENT_SOCK
        image: faucet/faucet:1.9.6
        name: faucet
        ports:
        - containerPort: 6653
        - containerPort: 9302
        resources: {}
        volumeMounts:
        - mountPath: /var/log/faucet
          name: faucet-claim0
        - mountPath: /etc/faucet
          name: faucet-{{ .Values.Instance }}-configuration
      restartPolicy: Always
      volumes:
      - name: faucet-claim0
        persistentVolumeClaim:
          claimName: faucet-claim0
      - name: faucet-{{ .Values.Instance }}-configuration
        configMap:
          name: faucet-{{ .Values.Instance }}-configuration
status: {}