apiVersion: v1
kind: Service
metadata:
  name:  {{ include "login-node.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: login-service
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
