apiVersion: v1
data:
  auth_openidc.conf: |
    OIDCProviderMetadataURL https://keycloak.utah-dev.slateci.net/auth/realms/ondemand/.well-known/openid-configuration
    OIDCClientID        "account"
    OIDCClientSecret    "1111111-1111-1111-1111-111111111111"
    OIDCRedirectURI      https://ondemand.utah-dev.slateci.net/oidc
    OIDCCryptoPassphrase "d14e5b4c8e6257ea81830f23c2be4633ad04d3af9816affdda6d8fec8ea926a000ca47b507587dc5"
    
    # Keep sessions alive for 8 hours
    OIDCSessionInactivityTimeout 28800
    OIDCSessionMaxDuration 28800

    # Set REMOTE_USER
    OIDCRemoteUserClaim preferred_username
    
    # Don't pass claims to backend servers
    OIDCPassClaimsAs environment

    # Strip out session cookies before passing to backend
    OIDCStripCookies mod_auth_openidc_session mod_auth_openidc_session_chunks mod_auth_openidc_session_0 mod_auth_openidc_session_1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-auth-config
