# Instance to label use case of XCache deployment
# Generates app name as "xcache-[Instance]"
# Enables unique instances of XCache in one namespace
Instance: ""

# The node (in your Kubernetes cluster) to schedule this instance on
# This hostname should match the host certificate provided in your SLATE secret
# Should match the FQDN of the node you want this instance to land on
NodeName: k8s-1.example.edu

Service:
  # Port that the service will utilize.
  Port: 1094

SiteConfig:
  Name: T3_US_NotreDame
  Origin: cmsxrootd.fnal.gov:1094
  Manager: ndcms.crc.nd.edu

Monitoring:
  Collector: xrootd.t2.ucsd.edu:9930

XCacheConfig:
  # The directory containing files to export from the cache
  RootDir: "/"
  # Server name used for monitoring and reporting
  ResourceName: ""
  # Local directory to be used as a cache
  # Space usage
  HighWaterMark: 0.95
  LowWaterMark: 0.90
  # The amount of memory XCache is allowed to use (in GB)
  RamSize: 16g
  # Minimal chunk size that will be prefetched/cached.
  BlockSize: 1M
  # to prefetch even chunks that were not requested
  Prefetch: 0
  # Write queue parameters
  WQBlocksPerLoop: 10
  WQThreads: 2
  # The name of the secret that was created for your XCache certificate
  # This must be created BEFORE deploying XCache
  CertSecret: xcache-cert-secret
  # Disable OSG monitoring and reporting
  DisableOSGMonitoring: true
  LocalRoot: /xcache/namespace
  CacheDirectories:
    - path: /data1/xcache
      type: data
    - path: /data2/xcache
      type: data
    - path: /data3/xcache
      type: data
    - path: /meta
      type: meta
