# Open OnDemand Configuration
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The SLATE instance value.
Instance: "global"

replicaCount: 1

setupKeycloak: true

# Keycloak volume parameters
volume:
  storageClass: local-path
  size: 50M

# LDAP/Kerberos setup and configuration
setupLDAP: true
generateUsers: false
ldap:
  connectionURL: "ldap://ldap.chpc.utah.edu"
  importUsers: "true"
  rdnLDAPAttribute:  "uid"
  uuidLDAPAttribute: "uidNumber"
  userObjectClasses: "inetOrgPerson, organizationalPerson"
  usersDN: "dc=chpc,dc=utah,dc=edu"
kerberos:
  realm: "AD.UTAH.EDU"
  serverPrincipal: "HTTP/utah-dev.chpc.utah.edu@AD.UTAH.EDU"
  krb5_server: "kdc1.chpc.utah.edu:88,kdc2.chpc.utah.edu:88,kdc3.chpc.utah.edu:88,kdc4.chpc.utah.edu:88,kdc5.chpc.utah.edu:88"
  keyTab: "/etc/krb5.keytab"
  kerberosPasswordAuth: "true"
  debug: "true"

# Resource management and cluster definition files
# Add another cluster section for each backend cluster you wish to connect to
clusters:
  - cluster:
      name: "slate-node1"
      host: "slate-node1.chpc.utah.edu"
      enableHostAdapter: true
      job:
        ssh_hosts: "slate-node1.chpc.utah.edu"
        singularity_bin: /bin/singularity
        singularity_bindpath: /etc,/media,/mnt,/opt,/run,/srv,/usr,/var,/home
        singularity_image: /opt/centos7.sif  # Something like centos_7.6.sif
        tmux_bin: /usr/bin/tmux
      basic_script: 
        - '#!/bin/bash'
        - 'set -x'
        - 'export XDG_RUNTIME_DIR=$(mktemp -d)'
        - '%s'
      vnc_script: 
        - '#!/bin/bash'
        - 'set -x'
        - 'export PATH="/opt/TurboVNC/bin:$PATH"'
        - 'export WEBSOCKIFY_CMD="/usr/bin/websockify"'
        - 'export XDG_RUNTIME_DIR=$(mktemp -d)'
        - '%s'
      set_host: "$(hostname)"
  - cluster:
      name: "Notchpeak"
      host: "notchpeak.chpc.utah.edu"
      enableHostAdapter: false

# Host regex (Should capture hostnames of all backend clusters)
host_regex: '[\w.-]+\.(peaks|arches|int.chpc.utah.edu|chpc.utah.edu)'

# Configure remote desktop and other applications (Requires LinuxHost Adapter)
enableHostAdapter: true
advanced:
  desktop: "mate"
  node_selector_label: "ssd"
  ssh_keys_GID: 993
# Provide names for each host key stored in your secret
  secret_name: "ssh-key-secret"
  host_keys:
    - host_key:
        name: "ssh_host_ecdsa_key"
    - host_key:
        name: "ssh_host_ecdsa_key.pub"
    - host_key:
        name: "ssh_host_ed25519_key"
    - host_key:
        name: "ssh_host_ed25519_key.pub"
    - host_key:
        name: "ssh_host_rsa_key"
    - host_key:
        name: "ssh_host_rsa_key.pub"
# Configure file sharing (Choose either to use autofs or a single NFS mount)
  autofs: true
  NFS: false
  fileSharing:
# If NFS enabled
    nfs_path: "/uufs/chpc.utah.edu/common/home"
    ip_addr: 127.0.0.1
# If autofs enabled
    autofs_path: "/uufs/chpc.utah.edu/common/home"
    autofs_mounts: 
      - '* -nolock,hard,intr,timeo=16,retrans=8,nfsvers=3 \'
      - '           cottonwood-vg10-2-lv1.chpc.utah.edu:/uufs/cottonwood/common/cottonwood-vg10-2-lv1/slate/&'

# Configure additional test users to be added to the Keycloak user database
# Ensure that these users do not exist on backend clusters
testUsers:
  - user:
      name: "test"
      tempPassword: "test"

### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
  Cluster:
    DNSName: "utah-dev.slateci.net"
### SLATE-END ###
      
