# Open OnDemand Configuration
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The SLATE instance value.
Instance: "slate"

replicaCount: 1

# Keycloak volume parameters
volume:
  storageClass: local-path
  size: 50M

# LDAP/Kerberos setup and configuration
setupLDAP: true
ldap:
  connectionURL: "ldap://ldap.example.net"
  importUsers: "true"
  rdnLDAPAttribute:  "uid"
  uuidLDAPAttribute: "uidNumber"
  userObjectClasses: "inetOrgFoo, orgBar"
  ldapSearchBase: "dc=foo,dc=bar"
  usersDN: "ou=People,dc=foo,dc=bar"
kerberos:
  realm: "AD.EXAMPLE.NET"
  serverPrincipal: "kdc1.example.net:80,kdc2.example.net:80"
  keyTab: "/etc/krb5.keytab"
  kerberosPasswordAuth: "true"
  debug: "true"

# Resource management and cluster definition files
# Add another cluster section for each backend cluster you wish to connect to
clusters:
  - cluster:
      name: "Node1"
      host: "node1.example.net"
      enableHostAdapter: true
      job:
        ssh_hosts: "node1.example.net"
        site_timeout: 14400
        singularity_bin: /bin/singularity
        singularity_bindpath: /etc,/media,/mnt,/opt,/run,/srv,/usr,/var,/home
        singularity_image: /opt/centos_7.sif
        tmux_bin: /usr/bin/tmux
      basic_script: 
        - '#!/bin/bash'
        - 'set -x'
        - 'export XDG_RUNTIME_DIR=$(mktemp -d)'
        - '%s'
      vnc_script: 
        - '#!/bin/bash'
        - 'set -x'
        - 'export PATH="/opt/TurboVNC/bin:$PATH"'
        - 'export WEBSOCKIFY_CMD="/usr/bin/websockify"'
        - 'export XDG_RUNTIME_DIR=$(mktemp -d)'
        - '%s'
      set_host: "$(hostname)"
  - cluster:
      name: "Node2"
      host: "node2.example.net"
      enableHostAdapter: false

# Host regex (Should capture hostnames of all backend clusters)
host_regex: '[\w.-]+\.(foo|bar|example.net|example.edu)'

# Configure remote desktop and other applications (Advanced)
# This is optional configuration which requires the linuxHost Adapter
enableHostAdapter: true
advanced:
  desktop: "mate"
  node_selector_label: "ood"
  ssh_keys_GID: 993
# Provide names for each host key stored in your secret
  secret_name: "ssh-key-secret"
  host_keys:
    - host_key:
        name: "ssh_host_ecdsa_key"
    - host_key:
        name: "ssh_host_ecdsa_key.pub"
    - host_key:
        name: "ssh_host_ed25519_key"
    - host_key:
        name: "ssh_host_ed25519_key.pub"
    - host_key:
        name: "ssh_host_rsa_key"
    - host_key:
        name: "ssh_host_rsa_key.pub"
# Filesystem distribution
  autofs: true
  fileSharing:
    nfs_shares: # Use '\\' to escape a backslash character 
      - '* -nolock,hard,ro \\'
      - '           example.net:/foo/bar/& \\'
      - '           example.edu:/foo/bar/&'

# Configure additional test users to be added to the Keycloak user database
# Ensure that these users do not exist on backend clusters
testUsers:
  - user:
      name: "test"
      group: "test1"
      groupID: "1000"
      tempPassword: "test"

### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
  Cluster:
    DNSName: "foo.bar.example.net"
### SLATE-END ###
      
