# Instance to label use case of Frontier Squid deployment
# Generates app name as "osg-frontier-squid-[Instance]"
# Enables unique instances of Frontier Squid in one namespace
Instance: global

### SLATE-START ###
# Deployment specific information used for the SLATE methodology
SLATE:
  # The name of the cluster that the application is being deployed on
  Cluster:
    Name: mini-SLATE
  LocalStorage: false
### SLATE-END ###

Service:
  # Port that the service will utilize.
  Port: 3128
  # Controls how your service is can be accessed. Valid values are:
  # - LoadBalancer - This ensures that your service has a unique, externally
  #                  visible IP address
  # - NodePort - This will give your service the IP address of the cluster node 
  #              on which it runs. If that address is public, the service will 
  #              be externally accessible. Using this setting allows your 
  #              service to share an IP address with other unrelated services. 
  # - ClusterIP - Your service will only be accessible on the cluster's internal 
  #               kubernetes network. Use this if you only want to connect to 
  #               your service from other services running on the same cluster. 
  ExternalVisibility: NodePort
  # External port on which the service will be accessible when using NodePort
  # visibility. The default behavior, if this value is not set, is for 
  # Kubernetes to select a port randomly from within its NodePort range. Note
  # that attempting to select a port manually outside the NodePort range will
  # fail. 
  #NodePort: 31200

SquidConf:
  # The amount of memory (in MB) that Frontier Squid may use on the machine.
  # Per Frontier Squid, do not consume more than 1/8 of system memory with Frontier Squid
  CacheMem: 128
  # The amount of disk space (in MB) that Frontier Squid may use on the machine.
  # The default is 10000 MB (10 GB), but more is advisable if the system supports it.
  # Current limit is 999999 MB, a limit inherent to helm's number conversion system.
  CacheSize: 10000
  # The range of incoming IP addresses that will be allowed to use the proxy.
  # Multiple ranges can be provided, each seperated by a space.
  # Example: 192.168.1.1/32 192.168.2.1/32
  # Use 0.0.0.0/0 for open access.
  # The default set of ranges are those defined in RFC 1918 and typically used 
  # within kubernetes clusters. 
  IPRange: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
  
  # Hostname (FQDN) for the cluster node you want this instance to schedule on.
  # This will also be the hostname used to access the squid if ExternalVisibility is set to NodePort
  # Set this to null to be randomly assigned an available node
NodeSelection:  
  Hostname: null

  #If extra configuration options are wanted, the values for said options should be inserted here
  #By default these extra configuration options are turned off, set ExtraConfig to True to turn them on
ExtraConfig: True

ExtraConf:
  acl_NET_LOCAL_src: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 129.74.0.0/16"
  Workers: 4
  Cache_Mem: "128 MB"
  Cpu_Affinity_Map: "process_numbers=1,2,3,4 cores=2,3,4,5"
  Visible_Hostname: "'`uname -n`'/${process_number}"
  Logfile_Rotate: "10"
