# Instance to label use case of Frontier Squid deployment
# Generates app name as "osg-frontier-squid-[Instance]"
# Enables unique instances of Frontier Squid in one namespace
Instance: ""

### SLATE-START ###
# Deployment specific information used for the SLATE methodology
SLATE:
  # The name of the cluster that the application is being deployed on
  Cluster:
    Name: mini-SLATE
  LocalStorage: false
  Instance:
    ID: "untagged"
### SLATE-END ###

# Supported values are e.g. 'release' or 'testing' or 'development'. Default is
# 'release'. Consult the opensciencegrid/frontier-squid docker image for other
# tags.
#ImageTag: release

Service:
  # Port that the service will utilize.
  Port: 3128
  # Controls how your service is can be accessed. Valid values are:
  # - LoadBalancer - This ensures that your service has a unique, externally
  #                  visible IP address
  # - NodePort - This will give your service the IP address of the cluster node 
  #              on which it runs. If that address is public, the service will 
  #              be externally accessible. Using this setting allows your 
  #              service to share an IP address with other unrelated services. 
  # - ClusterIP - Your service will only be accessible on the cluster's internal 
  #               kubernetes network. Use this if you only want to connect to 
  #               your service from other services running on the same cluster. 
  ExternalVisibility: NodePort
  # External port on which the service will be accessible when using NodePort
  # visibility. The default behavior, if this value is not set, is for 
  # Kubernetes to select a port randomly from within its NodePort range. Note
  # that attempting to select a port manually outside the NodePort range will
  # fail. 
  #NodePort: 31200
  # Port the service will use for serving monitoring data
  MonitoringPort: 3401
  # External port on which the monitoring will be accessible when using
  # NodePort visibility. The default behavior, if this value is not set, is for 
  # Kubernetes to select a port randomly from within its NodePort range. Note
  # that attempting to select a port manually outside the NodePort range will
  # fail. 
  #MonitoringNodePort: 31201

SquidConf:
  # The number of CPU cores allocated to the Squid application. The default is 2.
  CPU: 1
  # The amount of memory (in MB) that Frontier Squid may use on the machine.
  # Per Frontier Squid, do not consume more than 1/8 of system memory with Frontier Squid
  CacheMem: 4096
  # The maximum size (in KB) for an in-memory object
  # Default: 512
  #MaximumObjectSizeInMemory: 512
  # The amount of disk space (in MB) that Frontier Squid may use on the machine.
  # The default is 10000 MB (10 GB), but more is advisable if the system supports it.
  # Current limit is 999999 MB, a limit inherent to helm's number conversion system.
  CacheSize: 10000
  # If True, the application will expect a hostPath to be present and writeable
  # at /var/cache/squid on the host. 
  # CacheDirOnHost: False
  # This is the total storage (in MiB) beyound the CacheSize. If logging is disabled or if
  # Pod.UseHostpathLogDir set to true(see below), 1024 and 5120 would be reasonable values
  # for request and limit respectively. With logging enabled and Pod.UseHostpathLogDir set
  # to false, higher values would be advisable if target cluster or node supports that.
  # The below default values assume that logging is enabled.
  RequestEphemeralSize: 7000
  LimitEphemeralSize: 12000
  # The range of incoming IP addresses that will be allowed to use the proxy.
  # Multiple ranges can be provided, each seperated by a space.
  # Example: 192.168.1.1/32 192.168.2.1/32
  # Use 0.0.0.0/0 for open access.
  # The default set of ranges are those defined in RFC 1918 and typically used 
  # within kubernetes clusters. 
  IPRange: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16

  # The regular expressiion to restrict outbound traffic
  #RESTRICT_DEST: "^(((cms|atlas).*frontier.*)\\.cern\\.ch)|frontier.*\\.racf\\.bnl\\.gov$"

  # The range of IP addresses that will be allowed to query the service's monitoring data.
  # Multiple ranges can be provided, each seperated by a space.
  # Example: 128.142.0.0/16 188.185.0.0/17
  MonitoringIPRange: 127.0.0.1/32

  # Write all access_log messages to standard output where they can be viewed with the 
  # Docker/Kubernetes/SLATE log mechanisms, instead of to a file inside the container. 
  LogToStdout: True
  # To disable logging, set the below flag to true
  #DisableLogging: False
  # truncates log file every 2 minutes.
  CleanLog: False
  # Configure the number of names to use when rotating logfiles
  Logfile_Rotate: "30"
  # Set the max size for the access log file
  MaxAccessLog: "20M"  
  # Use local hostpath log dir
  # The directory "/var/log/slate/hostPath/osg-frontier-squid" must exist with rwx
  # permissions for uid:10941 on the target node.
  # This configuration has no effect when NodeSelection.Hostname is not set below.
  UseHostpathLogDir: False
  # Set the minimum object size on disk (e.g. 1MB)
  #DiskCacheMinObjSize: "1000000"
  # Disable the disk cache entirely
  DisableDiskCache: False

NodeSelection:  
  # Hostname (FQDN) for the cluster node you want this instance to schedule on.
  # This will also be the hostname used to access the squid if ExternalVisibility is set to NodePort
  # Set this to null to be randomly assigned an available node 
  Hostname: null
  # Set the below flag to true if you want to expose defautl port on the target node
  # Open default monitoring port (3401) -- This flag has no effect if Hostname is not set above in this conf file.
  OpenDefaultMonPort: False

#Allow the frontier-squid instance to send an alert before container stops.
#The alert will be sent to the configured value for AaasServer, by default
#"aaas.atlas-ml.org", and those who subscribed to the alert category will get
#notified. 
#To enable the alarm feature, set the proper value for 'Site' below. 
#Prerequisites: The above Instance and NodeSelection.Hostname config variables
#need to be set to some proper values.
Alarm:
  Site: null
  AaasServer: aaas.atlas-ml.org

Pod:
  # Set to true if you want to use the host's timezone settings. This would affect the timestamps of log messages.
  # Default timezone is UTC.
  UseHostTimezone: false
