apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  {{- if .Values.adminPassword }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  ldap-toml: {{ .Values.ldap.config | b64enc | quote }}
