apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "globus-connect.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "globus-connect.fullname" . }}
      chart: {{ template "globus-connect.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "globus-connect.fullname" . }}
        chart: {{ template "globus-connect.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      volumes:
        - name: {{ template "globus-connect.fullname" . }}-config
          configMap:
            name: {{ template "globus-connect.fullname" . }}-config
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup
        - name: tmp-conf
          emptyDir: {}
        - name: varlog
          emptyDir: {}
      hostNetwork: true
      initContainers:
      - name: init-configmap
        image: busybox
        command: ['sh', '-c', 'cp /etc/globus/globus-connect-server.conf /tmp/globus/globus-connect-server.conf; sed -i "s/%(GLOBUS_PASSWORD)s/$GLOBUS_PASSWORD/g" /tmp/globus/globus-connect-server.conf' ]
        volumeMounts:
          - name: {{ template "globus-connect.fullname" . }}-config
            mountPath: /etc/globus
          - name: tmp-conf
            mountPath: /tmp/globus
        env:
          - name: GLOBUS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.GlobusConnect.Client.Secret }}
                key: globus-password
      containers:
      - name: "gcs5"
        image: slateci/gcs5:latest
        securityContext:
          privileged: true
        #command: ["/usr/bin/supervisord","-n"]
        command: ["/usr/sbin/init"]
        volumeMounts:
          - name: {{ template "globus-connect.fullname" . }}-config
            mountPath: /etc/globus
          - name: cgroups
            mountPath: /sys/fs/cgroup
            readOnly: true
          - name: tmp-conf
            mountPath: /tmp/globus
          - name: varlog
            mountPath: /var/log
      - name: logs
        image: busybox
        command: [ 'sh', '-c', 'sleep 5; tail -f /var/log/globus-connect-server.log' ]
        volumeMounts:
          - name: varlog
            mountPath: /var/log
