apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-hosted-ce.fullname" . }}
  labels:
    app: {{ template "osg-hosted-ce.name" . }}
    chart: {{ template "osg-hosted-ce.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-hosted-ce.name" . }}
      chart: {{ template "osg-hosted-ce.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels: 
        app: {{ template "osg-hosted-ce.name" . }}
        chart: {{ template "osg-hosted-ce.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      volumes:
      - name: osg-hosted-ce-{{ .Values.Instance }}-configuration
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-configuration
      {{ if .Values.CustomizationScript }}
      - name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
      {{ end }}
      {{ if .Values.GridmapOverride }}
      - name: osg-hosted-ce-{{ .Values.Instance }}-grid-mapfile
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-grid-mapfile
      {{ end }}
      - name: bosco-ssh-private-key-volume
        secret: 
          secretName: {{ .Values.Cluster.PrivateKeySecret }}
          items:
          - key: bosco.key
            path: bosco.key
            mode: 256
      {{ if .Values.BoscoOverrides.Enabled }}
      {{ if .Values.BoscoOverrides.RepoNeedsPrivKey }}
      - name: osg-hosted-ce-{{ .Values.Instance }}-gitkey
        secret:
          secretName: {{ .Values.BoscoOverrides.GitKeySecret }}
          items:
          - key: git.key
            path: git.key
            mode: 256 
      {{ end }}
      {{ end }}
      {{ if .Values.HTTPLogger.Enabled }}
      - name: log-volume
        emptyDir: {} 
      - name: osg-hosted-ce-{{ .Values.Instance }}-logpasswd
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-logpasswd
      {{ end }}
      containers:
      {{ if .Values.HTTPLogger.Enabled }}
      - name: logging-sidecar
        volumeMounts:
        - name: log-volume
          mountPath: /usr/share/nginx/html
        - name: osg-hosted-ce-{{ .Values.Instance }}-logpasswd
          mountPath: /etc/nginx/auth
        ports: 
        - name: logs
          containerPort: 8080
          protocol: TCP
        image: "nginx:1.15.9"
        command: ["/bin/bash"]
        args: ["-c", "sed -i -e 's|\\(listen[^0-9]*\\)80|\\1 8080|' -e 's|index  index.html index.htm|autoindex  on|'  -e '/location \\/ {/ a\\        auth_basic           \"Restricted\";\\\n\\        auth_basic_user_file /etc/nginx/auth/htpasswd;' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
        imagePullPolicy: IfNotPresent
      {{ end }}
      - name: osg-hosted-ce
        image: opensciencegrid/hosted-ce:fresh
        volumeMounts:
        - name: osg-hosted-ce-{{ .Values.Instance }}-configuration
          mountPath: /tmp/99-local.ini
          subPath: 99-local.ini
        - name: bosco-ssh-private-key-volume
          mountPath: /etc/osg/bosco.key
          subPath: bosco.key
        {{ if .Values.HTTPLogger.Enabled }}
        - name: log-volume
          mountPath: /var/log/condor-ce
        {{ end }}
        {{ if .Values.BoscoOverrides.RepoNeedsPrivKey }}
        - name: osg-hosted-ce-{{ .Values.Instance }}-gitkey
          mountPath: /etc/osg/git.key
          subPath: git.key
        {{ end }}
        {{ if .Values.CustomizationScript }}
        - name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
          mountPath: /tmp/{{ .Values.Cluster.Batch }}_local_submit_attributes.sh
          subPath: {{ .Values.Cluster.Batch }}_local_submit_attributes.sh
        {{ end }}
        {{ if .Values.GridmapOverride }}
        - name: osg-hosted-ce-{{ .Values.Instance }}-grid-mapfile
          mountPath: /etc/grid-security/grid-mapfile
          subPath: grid-mapfile
        {{ end }}
        {{ if .Values.HTTPLogger.Enabled }}
        initContainers:
        - name: logging-sidecar-init
          image: opensciencegrid/hosted-ce:fresh
          command: ['/bin/chown','condor:condor','/var/log/condor-ce']
          volumeMounts:
          - name: log-volume
            mountPath: /var/log/condor-ce
        {{ end }}
        ports:
        - name: htcondor-ce
          containerPort: 9619
          protocol: TCP
        - name: http # needed to get a cert issued from Let's Encrypt
          containerPort: 80
          protocol: TCP
        env:
        - name: _CONDOR_NETWORK_HOSTNAME
          value: {{ .Values.Networking.Hostname }}
        - name: CE_HOSTNAME
          value: {{ .Values.Networking.Hostname }}
        - name: ENDPOINT
          value: {{ .Values.Cluster.Endpoint }}
        - name: CE_CONTACT
          value: {{ .Values.Site.ContactEmail }}
        - name: CE_USERS
          value: {{ .Values.Cluster.Users }}
        {{ if .Values.CustomizationScript }}
        - name: LOCAL_ATTRIBUTES_FILE
          value: /tmp/{{ .Values.Cluster.Batch }}_local_submit_attributes.sh
        {{ end }}
        {{ if .Values.BoscoOverrides.Enabled }}
        - name: BOSCO_GIT_ENDPOINT
          value: {{ .Values.BoscoOverrides.GitEndpoint }}
        - name: BOSCO_DIRECTORY
          value: {{ .Values.BoscoOverrides.Subdirectory }}
        {{ end }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/local/bin/drain-ce.sh"]
