# Default values for perfsonar-checker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#A name for your instance (optional)
Instance: ''

NodeSelection:
  # the hostname of the node on which you want pod to run. (optional)
  # Default: null - the K8s scheduler will select a host for you  
  Hostname: null
# An optional feature that allows you to view full output of all tests.
# Default: Not Enabled
HTTPLogger: 
  Enabled: false

PerfsonarChecker:
  # Destinations to which the tests will run
  Dest1: "sl-um-ps01.slateci.io"
  Dest2: "uofu-ddc-dmz-latency.chpc.utah.edu"
  Dest3: "sl-uu-es1.slateci.io"

### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
### SLATE-END ###
