# Instance to label use case of Redis deployment
# Generates app name as "redis-[Instance]"
# Enables unique instances of Redis in one namespace
Instance: ""

# The following must be created *before* instantiating a Redis container. 
# Create a new file with the contents:
#   REDIS_PASSWORD=<password>
# And then create the credential with:
#   slate secret create <secret-name> --group <group> --cluster <cluster> \
#    --from-env-file <filename>
RedisCredentialSecret: redis-creds # maps to <secret-name> as in the above

service:
  type: NodePort
  port: 6379

# Defines what IP ranges can access the app
# If disabled all IP addresses can access the app
NetworkPolicy:
  Enable: false
  AllowedCIDRs:
    - 0.0.0.0/0
