Instance: ""

Site:
  Group: OSG
  Resource: UCHICAGO-SLATE
  ResourceGroup: UCHICAGO
  Sponsor: osg:100
  Contact: Lincoln Bryant
  ContactEmail: lincolnb@uchicago.edu
  City: Chicago
  Country: US
  Latitude: 41.8781
  Longitude: 87.6298

Cluster:
  Users: osg, cmsuser, usatlas2, glow
  Endpoint: lincolnb@slate-micro-condor.slateci.io
  PrivateKeySecret: lincolnb-bosco # maps to SLATE secret
  Batch: condor
  MaxJobs: 10

Storage:
  GridDir: /home/lincolnb/osg-wn-client
  WorkerNodeTemp: /tmp

Subcluster:
  Name: UCHICAGO-SLATE
  Memory: 1024
  CoresPerNode: 4
  MaxWallTime: 1440
  AllowedVOs: osg, cms, atlas, glow
  
Squid:
  Enabled: True
  Location: squid.grid.uchicago.edu
  
Networking:
  # The hostname that the CE should use. 
  # Appropriate A and PTR DNS records must exist.
  Hostname: ""
  # The preferred IP address which should be requested from the LoadBalancer. 
  # This may be left as null to express no preference. 
  # Setting this may be useful when redeploying a CE in order to try to get
  # back the same IP address that was used previously. 
  RequestIP: null

# Options to allow override of the bosco directory from arbitrary git repos
BoscoOverrides:
  Enabled: true
  GitEndpoint: git@gitlab.mwt2.org:osg/hosted-ce-config.git
  Subdirectory: OSG_US_NEWJERSEY_ELSA
  RepoNeedsPrivKey: true
  GitKeySecret: mwtGitLabSecret

# If you wish to allow yourself to submit to this CE with your personal grid
# proxy, you can put that in below. This will get directly mapped into
# /etc/grid-security/grid-mapfile
#
#GridmapOverride: |+
#  "/DC=foo/DC=bar/OU=Organic Units/OU=Users/CN=YourUserName" osg

# The following script will run on the _remote_ cluster when jobs are
# submitted. The script will get stored into:
#    ~${username}/bosco/glite/bin/${batch}_local_submit_attributes.sh
# on the remote cluster
#
#CustomizationScript: |+
#  #!/bin/sh 
#  ... 
