# Instance to label use case of XCache deployment
# Generates app name as "xcache-[Instance]"
# Enables unique instances of XCache in one namespace
Instance: global

Service:
  # Port that the service will utilize.
  Port: 1094
  # External IP that may access the service
  # 98.206.166.200 - localhost
  # 192.170.227.231 - ml node - root://xcache.mwt2.org:1094
  # 192.170.236.171 - river-dev
  # 192.170.236.158 - river
  ExternalIP: 98.206.166.200

SiteConfig:
  Name: Home
  InstanceID: xc_xps
  # CRIC protocol ID. 433 is a dummy value. 
  # can be looked up in this URL: https://atlas-cric.cern.ch/api/core/service/query/?json
  # Endpoints can be created here: https://atlas-cric.cern.ch/core/service/create/
  CRICprotocolID: 433

Monitoring:
  Collector: http://collector.atlas-ml.org:80
  GStreamCollector: collector.atlas-ml.org:9000 
  VPheartbeat: https://vps.cern.ch/liveness

XCacheConfig:
  # Local directories to be used as a cache
  
  CacheDirectories:
    # - path: /C/scratch/data
    - path: /tmp
  # MetaDirectory: /C/scratch/meta
  MetaDirectory: /tmp

  # Space usage
  HighWaterMark: 0.95
  LowWaterMark: 0.90
  
  # The amount of memory XCache is allowed to use (in GB)
  RamSize: 16g
  # Minimal chunk size that will be prefetched/cached.
  BlockSize: 1M
  # to prefetch even chunks that were not requested
  Prefetch: 0
  # Write queue parameters
  WQBlocksPerLoop: 10
  WQThreads: 2
  # The name of the secret that was created for your XCache certificate
  # This must be created BEFORE deploying XCache
  CertSecret: xcache-cert-secret


image:
  repository: ivukotic/docker-xcache
  tag: latest  
  pullPolicy: Always
  # repository: docker-xcache
  # tag: latest
  # pullPolicy: Never
