# Describes a Kubernetes deployment of a container running Telegraf.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "telegraf.fullname" . }}
  labels:
    app: {{ template "telegraf.name" . }}
    chart: {{ template "telegraf.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "telegraf.name" . }}
      instance: {{ .Values.Instance | quote }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "telegraf.name" . }}
        chart: {{ template "telegraf.chart" . }}
        instance: {{ .Values.Instance | quote }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: telegraf
          image: karlnewell/tsds-telegraf
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/telegraf/conf.d
              name: telegraf-volume 
      volumes:
        - name: telegraf-volume
          # populate volume with config map data
          configMap:
            name: telegraf-{{ .Values.Instance }}-configuration
