# Label for this particular deployed instance
# Results in a name like "stashcache-[Instance]"
# Enables multiple instances of StashCache in one namespace
Instance: global

Service:
  Port: 1094

Site:
  Name: "stashcache"

StashCache:
  # Local directory to be used as a cache
  CacheDirectory: /scratch
  # Space usage
  HighWaterMark: 0.95
  LowWaterMark: 0.80
  # The amount of memory the cache is allowed to use (in GB)
  RamSize: 1g
  # Minimal chunk size that will be prefetched/cached.
  BlockSize: 1M
  # to prefetch chunks that were not requested
  Prefetch: 0

stashcacheConfig: |-
  set eSITENAME=$STASHCACHE_SITE_NAME
  set eRAMSIZE=$STASHCACHE_RAMSIZE
  set eSPACELOWWM=$STASHCACHE_SPACE_LOW_WM
  set eSPACEHIGHWM=$STASHCACHE_SPACE_HIGH_WM
  set eBLOCKSIZE=$STASHCACHE_BLOCKSIZE
  set ePREFETCH=$STASHCACHE_PREFETCH
  set eMONITORDEST=$STASHCACHE_MONITORING_ENDPOINT
  all.export    /
  xrd.allow     host *
  sec.protocol  host
  all.adminpath /var/spool/xrootd
  all.pidpath   /var/run/xrootd

  # A lot of stale http connections from caltech
  #xrd.timeout  idle 10m

  xrootd.trace emsg login stall
  xrd.trace    info
  ofs.trace    info
  http.trace   info

  ofs.osslib   libXrdPss.so
  pss.origin   redirector.osgstorage.org:1094
  pss.cachelib libXrdFileCache.so
  #pss.setopt DebugLevel 1

  # Increase debug level
  pss.setopt DebugLevel 3
  pss.trace  info

  if defined ?~LOCAL_CACHE_DIR
  set cachedir = $LOCAL_CACHE_DIR
  else
  set cachedir = /xrdpfc/stash
  fi

  oss.localroot $(cachedir)

  if defined ?~REDIRECTOR && named stashcache-cache-server
  set redir = $REDIRECTOR
  all.manager $redir
  all.role server
  fi

  if exec cmsd
  cms.trace defer files redirect stage
  fi

  if defined ?~DATA1
  set stashpath1 = $DATA1
  oss.space public $stashpath1
  fi

  if defined ?~DATA2
  set stashpath2 = $DATA2
  oss.space public $stashpath2
  fi

  if defined ?~DATA3
  set stashpath3 = $DATA3
  oss.space public $stashpath3
  fi

  if defined ?~DATA4
  set stashpath4 = $DATA4
  oss.space public $stashpath4
  fi

  if defined ?~DATA5
  set stashpath5 = $DATA5
  oss.space public $stashpath5
  fi

  if defined ?~DATA6
  set stashpath6 = $DATA6
  oss.space public $stashpath6
  fi

  if defined ?~DATA7
  set stashpath6 = $DATA7
  oss.space public $stashpath7
  fi

  if defined ?~RAMSIZE
     set eRAMSIZE = $RAMSIZE
  else
     set eRAMSIZE = 1g
  fi

  if defined ?~BLOCKSIZE
     set eBLOCKSIZE = $BLOCKSIZE
  else
     set eBLOCKSIZE = 512k
  fi

  if defined ?~PREFETCH
     set ePREFETCH = $PREFETCH
  else
     set ePREFETCH = 128
  fi

  if defined ?~SPACELOWWM
     set eSPACELOWWM = $SPACELOWWM
  else
     set eSPACELOWWM = 0.93
  fi

  if defined ?~SPACEHIGHWM
     set eSPACEHIGHWM = $SPACEHIGHWM
  else
     set eSPACEHIGHWM = 0.98
  fi

  # Config for v2
  pfc.blocksize $eBLOCKSIZE
  pfc.ram       $eRAMSIZE
  pfc.prefetch  $ePREFETCH
  pfc.diskusage $eSPACELOWWM $eSPACEHIGHWM

  pfc.trace     debug

  # Enable the authorization module, even if we have an unauthenticated instance.
  ofs.authorize 1
  acc.audit deny grant
  xrootd.seclib /usr/lib64/libXrdSec.so

  if defined ?~XRDHTTPPORT
     set eXRDHTTPPORT = $XRDHTTPPORT
  else
     set eXRDHTTPPORT = 8000
  fi

  if exec xrootd && named stashcache-cache-server-auth
     sec.protocol /usr/lib64 gsi \
         -certdir:/etc/grid-security/certificates \
         -cert:/etc/grid-security/xrd/xrdcert.pem \
         -key:/etc/grid-security/xrd/xrdkey.pem \
         -crl:1 \
         -authzfun:libXrdLcmaps.so \
         -authzfunparms:--lcmapscfg,/etc/xrootd/lcmaps.cfg,--loglevel,5|useglobals \
         -gmapopt:10 \
         -authzto:3600

     xrd.port 8444
     setenv X509_USER_PROXY = /tmp/x509up_xrootd
     acc.authdb /etc/xrootd/Authfile-auth
     sec.protbind * gsi
     xrd.protocol http:8444 libXrdHttp.so
     pss.origin xrootd-local.unl.edu:1094

     http.cadir /etc/grid-security/certificates
     http.cert /etc/grid-security/xrd/xrdcert.pem
     http.key /etc/grid-security/xrd/xrdkey.pem
     http.secxtractor /usr/lib64/libXrdLcmaps.so
  else if exec xrootd
  #else if named stashcache-cache-server
     xrd.port $eXRDHTTPPORT
     acc.authdb /etc/xrootd/Authfile-noauth
     xrd.protocol http:$eXRDHTTPPORT libXrdHttp.so
     sec.protbind  * none
  fi

  http.listingdeny yes
  http.staticpreload http://static/robots.txt /etc/xrootd/stashcache-robots.txt

  # Tune the client timeouts to more aggressively timeout.
  pss.setopt ParallelEvtLoop 10
  pss.setopt RequestTimeout 25
  pss.setopt ConnectTimeout 25
  pss.setopt ConnectionRetry 2

  if defined ?~MONITORDEST
     set eMONITORDEST = $MONITORDEST
  else
     set eMONITORDEST = uct2-collectd.mwt2.org
  fi
  #XRootD stats for Ilja - added by Marian 04-15-2016
  xrd.report $(eMONITORDEST):9931
  #xrootd.monitor all auth flush 30s window 5s fstat 60 lfn ops xfr 5 dest redir fstat info user uct2-collectd.mwt2.org:9930
  #Added by Marian 02-22-2018
  xrootd.monitor all auth flush 30s window 5s fstat 5 lfn ops xfr 5 dest redir fstat info user uct2-collectd.mwt2.org:9930 dest fstat info user xrd-mon.osgstorage.org:9930

  if defined ?~SITENAME
  set sitename = $SITENAME
  all.sitename $sitename
  fi

