apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "stashcache.fullname" . }}
  labels:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "stashcache.name" . }}
      chart: {{ template "stashcache.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  template:
    metadata:
      labels:
        app: {{ template "stashcache.name" . }}
        chart: {{ template "stashcache.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
    spec:
      volumes:
      - name: stashcache-config
        configMap:
          name: {{ template "stashcache.fullname" . }}-config
          items:
          - key: Authfile-noauth
            path: Authfile-noauth
          - key: Authfile-auth
            path: Authfile-auth
          - key: stashcache-robots.txt
            path: stashcache-robots.txt
          - key: xcache_image_init.sh
            path: xcache_image_init.sh
          - key: 90-local.cfg
            path: 90-local.cfg
          defaultMode: 493
      - name: stashcache-data
        {{ if .Values.StashCache.CacheDirectory }}
        hostPath:
          path: {{ .Values.StashCache.CacheDirectory }}
        {{ else }}
        emptyDir: {}
        {{ end }}  
      {{ if .Values.hostCertSecret}}
      - name: host-certificate
        secret:
          secretName: {{ .Values.hostCertSecret }}
          items:
          - key: hostcert.pem
            path: hostcert.pem
          - key: hostkey.pem
            path: hostkey.pem
      {{ end }}
      containers:
      - name: stashcache
        image: opensciencegrid/stash-cache:20200727-1347
        imagePullPolicy: Always
        env:
        - name: XC_ROOTDIR
          value: "/stash"
        - name: XC_RESOURCENAME
          value: {{ .Values.Site.Name | quote }}
        volumeMounts:
        - name: stashcache-config
          mountPath: "/etc/xrootd/Authfile-noauth"
          subPath: Authfile-noauth
        - name: stashcache-config
          mountPath: "/etc/xrootd/Authfile-auth"
          subPath: Authfile-auth
        - name: stashcache-config
          mountPath: "/etc/xrootd/stashcache-robots.txt"
          subPath: stashcache-robots.txt
        - name: stashcache-config
          mountPath: "/etc/osg/image-config.d/20-image-init.sh"
          subPath: xcache_image_init.sh
        - name: stashcache-config
          mountPath: "/etc/xrootd/config.d/90-local.cfg"
          subPath: 90-local.cfg
        - mountPath: "/stash"
          name: stashcache-data
          readOnly: false
        {{ if .Values.hostCertSecret }}
        - mountPath: /etc/grid-security/hostcert.pem
          name: host-certificate
          readOnly: true
          subPath: hostcert.pem 
        - mountPath: /etc/grid-security/hostkey.pem
          name: host-certificate
          readOnly: true
          subPath: hostkey.pem
        {{ end }}
        livenessProbe:
          tcpSocket:
            port: 1094
          initialDelaySeconds: 180
          periodSeconds: 60
        ports:
        - containerPort: 1094
        - containerPort: 8000
