Instance: ""

# The following must be created *before* instantiating a GCSv4 container. 
# Create a new file with the contents:
#   GLOBUS_USER=<username>
#   GLOBUS_PASSWORD=<password>
# And then create the credential with:
#   slate secret create <secret-name> --group <group> --cluster <cluster> \
#    --from-env-file <filename>
GlobusCredentialSecret: globus-creds # maps to <secret-name> as in the above

# The following file must contain usernames and encrypted passwords for any 
# users who may log in to the system. This user will be used to generate a
# MyProxy certificate for the end user who will transfer files.
# The file must follow passwd(5) format, with one user per line with an 
# encrypted password in the second field:
#   slateci:ENCRYPTEDPASSWORDHERE:1001:1001:SLATE CI:/home/slateci:/bin/bash
# Once this file has been created, store it as a SLATE secret with:
#   slate secret create <secret-name> --group <group> --cluster <cluster> \
#     --from-file <filename>
GlobusPasswdSecret: globus-passwd # maps to <secret-name> as in the above

# The below configuration approximately maps to the GCS configuration file
# You can customize this to your liking.
GlobusConfig:
  GridFTP:
    # Specify the server name, alternatively specify the server name and port
    #Server: 
    IncomingPortRange: 50000,51000
    RestrictPaths: ""
  MyProxy:
    # Specify the server name, alternatively specify the server name and port
    #Server: 
  Endpoint:
    Public: True
    Name: "%(SHORT_HOSTNAME)s"
    DefaultDirectory: /~/
 # These are unimplemented for now. If it is relevant please let us know.
 # Security:
 #   FetchCredentialFromRelay: True
 #   IdentityMethod: "MyProxy"
 # 

# The path at which the storage should be mounted. 
ExternalPath: /export
# The path for a backing filesystem to be mounted from the host system. 
InternalPath: /mnt
# The name of a PersistentVolumeClaim which should be mounted as backing storage.
PVCName: 
# If set, use a nodeSelector (`globus=true`) to run only on a matching nodes. 
# This is useful when only certain nodes on the cluster mount the appropriate 
# backing filesystem. It may be desirable to turn this off when using a PVC as
# backing storage, since this tends not to tie to a specific node. 
UseNodeSelector: true
