Instance: ""

# The following must be created *before* instantiating a GCSv4 container. 
# Create a new file with the contents:
#   GLOBUS_USER=<username>
#   GLOBUS_PASSWORD=<password>
# And then create the credential with:
#   slate secret create <secret-name> --group <group> --cluster <cluster> \
#    --from-env-file <filename>
GlobusCredentialSecret: globus-creds # maps to <secret-name> as in the above

# The following file must contain usernames and encrypted passwords for any 
# users who may log in to the system. This user will be used to generate a
# MyProxy certificate for the end user who will transfer files.
# 
# The file must follow passwd(5) format. 
#
#                       **IMPORTANT** 
# If you are using MyProxy authentication, you will additionally
# need to include an encrypted password in the second field. 
#          
#   slateci:ENCRYPTEDPASSWORDHERE:1001:1001:SLATE CI:/home/slateci:/bin/bash
#
# Once this file has been created, store it as a SLATE secret with:
#
#   slate secret create <secret-name> --group <group> --cluster <cluster> \
#     --from-file <filename>
#
# OTHERWISE, if you are using CILogon authentication (default) you will need to
# provide an extended passwd(5)-format file with the users' X509 distinguished
# name (DN) in the final field, e.g.:
#   
#   slateci:x:1001:1001:SLATE CI:/home/slateci:/DC=org/DC=cilogon/C=US/O=UNIX University/CN=Charlie Root A1234
#
GlobusPasswdSecret: globus-passwd # maps to <secret-name> as in the above

# The below configuration approximately maps to the GCS configuration file
# You can customize this to your liking.
GlobusConfig:
  GridFTP:
    # Specify the server name, alternatively specify the server name and port
    #Server: 
    IncomingPortRange: 50000,51000
    RestrictPaths: ""
  Endpoint:
    Public: True
    Name: "%(SHORT_HOSTNAME)s"
    DefaultDirectory: /~/
  #Uncomment this field if you need to set the MyProxy server and/or port
  #MyProxyServer:
  Security:
     IdentityMethod: "CILogon"

# The path at which the storage should be mounted. 
ExternalPath: /export
# The path for a backing filesystem to be mounted from the host system. 
InternalPath: /mnt
# The name of a PersistentVolumeClaim which should be mounted as backing storage.
PVCName: 
# If set, use a nodeSelector to run only on a matching nodes. 
# This is useful when only certain nodes on the cluster mount the appropriate 
# backing filesystem. It may be desirable to turn this off when using a PVC as
# backing storage, since this tends not to tie to a specific node. 
# e.g., "NodeSelector: globus" will match nodes with "globus=true"
# NodeSelector: globus
