apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cms-xcache.fullname" . }}
  labels:
    app: {{ template "cms-xcache.name" . }}
    chart: {{ template "cms-xcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cms-xcache.name" . }}
      chart: {{ template "cms-xcache.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
    
  template:
    metadata:
      labels:
        app: {{ template "cms-xcache.name" . }}
        chart: {{ template "cms-xcache.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
    spec:
      volumes:
      {{ if .Values.HTTPLogger.Enabled }}
      - name: log-volume
        emptyDir: {}
      - name: logger-startup
        configMap:
          name: {{ template "cms-xcache.fullname" . }}-logging
      {{ end }}
      - name: xrootd-config
        configMap:
          name: {{ template "cms-xcache.fullname" . }}-xrootd-config
      - name: common-site-local
        configMap:
          name: {{ template "cms-xcache.fullname" . }}-common-site-local
      - name: x509-certs-volume
        secret:
          secretName: {{ required "XCache Certificate is required" .Values.XCacheConfig.CertSecret }}
          items:
          - key: hostkey
            path: hostkey.pem
            mode: 256 
          - key: hostcert
            path: hostcert.pem
      {{- range $nindex, $dir := .Values.XCacheConfig.CacheDirectories }}
      - name: {{ .type }}-{{ $nindex }}
        hostPath:
          path: {{ .path }}
          type: Directory
      {{- end }}
      - name: localroot
        hostPath:
          path: {{ required "LocalRoot is required" .Values.XCacheConfig.LocalRoot }}
          type: Directory
      nodeSelector: 
        kubernetes.io/hostname: {{ .Values.NodeName }} 
      containers:
        {{ if .Values.HTTPLogger.Enabled }}
        - name: logging-sidecar
          image: "nginx:1.15.9"
          command: ["/bin/bash"]
          args: ["/usr/local/bin/start-nginx.sh"]
          imagePullPolicy: IfNotPresent
          ports:
          - name: logs
            containerPort: 8080
            protocol: TCP
          volumeMounts:
          - name: log-volume
            mountPath: /usr/share/nginx/html
          - name: logger-startup
            mountPath: /usr/local/bin/start-nginx.sh
            subPath: start-nginx.sh
        {{ end }}
        - name: cms-xcache
          image: "opensciencegrid/cms-xcache:fresh"
          imagePullPolicy: Always
          env:
          {{ if .Values.HTTPLogger.Secret }}
          - name: HTPASSWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.HTTPLogger.Secret }}
                key: HTPASSWD
          {{ end }}
          - name: XC_ROOTDIR
            value: "{{ .Values.XCacheConfig.RootDir }}"
          - name: XC_RESOURCENAME
            value: "{{ .Values.XCacheConfig.ResourceName }}"
          - name: XC_SPACE_HIGH_WM
            value: "{{ .Values.XCacheConfig.HighWaterMark }}"
          - name: XC_SPACE_LOW_WM
            value: "{{ .Values.XCacheConfig.LowWaterMark }}"
          - name: XC_PORT
            value: "{{ .Values.Service.Port }}"
          - name: XC_RAMSIZE
            value: "{{ .Values.XCacheConfig.RamSize }}"
          - name: XC_BLOCKSIZE
            value: "{{ .Values.XCacheConfig.BlockSize }}"
          - name: XC_PREFETCH
            value: "{{ .Values.XCacheConfig.Prefetch }}"
          - name: XC_ROOTDIR
            value: "{{ .Values.XCacheConfig.LocalRoot }}"
          - name: WQ_BLOCKS_PER_LOOP
            value: "{{ .Values.XCacheConfig.WQBlocksPerLoop }}"
          - name: WQ_THREADS
            value: "{{ .Values.XCacheConfig.WQThreads }}"
          - name: DISABLE_OSG_MONITORING
            value: "{{ .Values.XCacheConfig.DisableOSGMonitoring }}"
          resources:
            requests:
              ephemeral-storage: "5Gi"
            limits:
              ephemeral-storage: "10Gi"
          ports:
            - name: xrootd
              containerPort: {{ .Values.Service.Port }}
              protocol: TCP
          volumeMounts:
          {{ if .Values.HTTPLogger.Enabled }}
          - name: log-volume
            mountPath: /var/log
          - name: log-volume
            mountPath: /var/log/condor
          - name: log-volume
            mountPath: /var/log/supervisor
          - name: log-volume
            mountPath: /var/log/xrootd
          {{ end }}
          - name: xrootd-config
            mountPath: /etc/xrootd/config.d/xrootd-config.cfg
            subPath: xrootd-config.cfg
          - name: common-site-local
            mountPath: /etc/xrootd/config.d/10-common-site-local.cfg
            subPath: 10-common-site-local.cfg
          - name: x509-certs-volume
            mountPath: /etc/grid-security/hostcert.pem
            subPath: hostcert.pem
          - name: x509-certs-volume
            mountPath: /etc/grid-security/hostkey.pem
            subPath: hostkey.pem
          - name: localroot
            mountPath: {{ required "LocalRoot is required" .Values.XCacheConfig.LocalRoot }}
          {{- range $nindex, $dir := .Values.XCacheConfig.CacheDirectories }}
          - name: {{ .type }}-{{ $nindex }}
            {{- if eq .type "data" }}
            mountPath: /xcache/data-{{ $nindex }}
            {{- else if eq .type "meta" }}
            mountPath: /xcache/meta-{{ $nindex }}
            {{- end }}
          {{- end }}
