kind: Service
apiVersion: v1
metadata:
  name: {{ template "stashcache.fullname" . }}
  labels:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  selector:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
  ports:
    - protocol: TCP
      name: xrootd
      port: {{ .Values.Service.Port }}
      targetPort: {{ .Values.Service.Port }}
      nodePort: 31094